project:
  type: website
  output-dir: .

website:
  title: "Not So Deep Photography"
  navbar:
    right:
      - text: Inicio
        href: index.qmd
      - text: Informaci√≥n
        href: about.qmd
      - text: Black And White
        href: bnw.qmd

format:
  html:
    theme: jornal
    css: styles.css
    toc: false

