project:
  type: website

website:
  title: "Daniel Sibaja"
  navbar:
    right:
      - text: Portfolio
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

