project:
  type: website
  output-dir: .

website:
  title: "Photo Portfolio"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Informaci√≥n
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

